collections:
  - name: community.general
  - name: community.postgresql
  - name: community.rabbitmq

  - name: hetzner.hcloud

roles:
  - name: libretime
    src: git+https://github.com/libretime/ansible-role-libretime.git
