---
collections:
  - name: community.general # https://github.com/ansible-collections/community.general
    version: 8.1.0
  - name: community.postgresql # https://github.com/ansible-collections/community.postgresql
    version: 3.3.0
  - name: community.rabbitmq # https://github.com/ansible-collections/community.rabbitmq
    version: 1.2.3
