---
collections:
  - name: community.general # https://github.com/ansible-collections/community.general
    version: 10.7.0
  - name: community.postgresql # https://github.com/ansible-collections/community.postgresql
    version: 4.1.0
  - name: community.rabbitmq # https://github.com/ansible-collections/community.rabbitmq
    version: 1.5.0
