---
- name: Install analyzer dependencies
  ansible.builtin.import_tasks: _dependencies.yml
  vars:
    packages_path: "{{ libretime_checkout_dest }}/analyzer"

- name: Install analyzer python package # noqa no-handler
  ansible.builtin.pip:
    name: >
      libretime-analyzer[{{ libretime_analyzer_pip_extras | join(',') }}]
      @ file://{{ libretime_checkout_dest }}/analyzer
    state: latest # noqa package-latest
    virtualenv: "{{ libretime_venv_dir }}"
  notify: Restart libretime
  when: libretime_checkout is changed

- name: Create analyzer entrypoint symlinks
  ansible.builtin.file:
    src: "{{ libretime_venv_dir }}/bin/libretime-analyzer"
    dest: /usr/local/bin/libretime-analyzer
    owner: root
    group: root
    state: link
    force: true

- name: Create analyzer home directory
  ansible.builtin.file:
    path: "{{ libretime_home }}/analyzer"
    owner: "{{ libretime_user }}"
    group: "{{ libretime_user }}"
    state: directory
    recurse: true

- name: Setup analyzer systemd service
  ansible.builtin.import_tasks: _systemd.yml
  vars:
    service_name: libretime-analyzer.service
    service_override: "{{ libretime_analyzer_systemd_override }}"
  notify: Restart libretime
