---
- name: Install analyzer dependencies
  ansible.builtin.import_tasks: _dependencies.yml
  vars:
    packages_path: "{{ libretime_checkout_dest }}/analyzer"

- name: Install analyzer python package # noqa no-handler
  ansible.builtin.pip:
    name: >
      libretime-analyzer[{{ libretime_analyzer_pip_extras | join(',') }}]
      @ file://{{ libretime_checkout_dest }}/analyzer
    state: latest # noqa package-latest
    virtualenv: "{{ libretime_venv | default(omit) }}"
  notify: Restart libretime
  when: libretime_checkout is changed

- name: Create analyzer home directory
  ansible.builtin.file:
    path: "{{ libretime_home }}/analyzer"
    owner: "{{ libretime_user }}"
    group: "{{ libretime_user }}"
    state: directory
    recurse: true

- name: Setup analyzer systemd service
  ansible.builtin.import_tasks: _systemd.yml
  vars:
    service_name: libretime-analyzer.service
  notify: Restart libretime
