---
- name: install apache2
  ansible.builtin.apt:
    name: [apache2]
    state: present

- name: disable default vhost
  ansible.builtin.file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2

- name: enable apache2 modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - proxy
    - proxy_http
    - proxy_uwsgi

- name: enable/start apache2
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: true
