---
- name: install apache2
  apt:
    name: [apache2]
    state: present

- name: disable default vhost
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2

- name: enable apache2 modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite

- name: deploy apache2 conf
  template:
    src: apache/libretime.conf.j2
    dest: /etc/apache2/sites-available/libretime.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: restart apache2

- name: enable apache2 conf
  file:
    src: /etc/apache2/sites-available/libretime.conf
    dest: /etc/apache2/sites-enabled/libretime.conf
    state: link
  notify: restart apache2

- name: enable/start apache2
  systemd:
    name: apache2
    state: started
    enabled: true
