---
- name: install api-client python package # noqa no-handler
  ansible.builtin.pip:
    name: "file://{{ libretime_checkout_dest }}/api-client"
  notify:
    - restart libretime-playout
  when: libretime_checkout is changed
