---
- name: Install api-client python package # noqa no-handler
  ansible.builtin.pip:
    name: "file://{{ libretime_checkout_dest }}/api-client"
    state: latest # noqa package-latest
  notify: Restart libretime
  when: libretime_checkout is changed
