---
- name: install liquidsoap
  ansible.builtin.apt:
    state: present
    name: liquidsoap
  when: libretime_liquidsoap_package_url is not defined

- name: install liquidsoap from url
  ansible.builtin.apt:
    state: present
    deb: "{{ libretime_liquidsoap_package_url }}"
  when: libretime_liquidsoap_package_url is defined
