---
- name: include distribution specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution_release }}.yml"

- name: exploding root_url
  ansible.builtin.set_fact:
    root_url_split: "{{ libretime_public_url | urlsplit }}"

- name: handling required fields for root_url
  ansible.builtin.set_fact:
    root_url_scheme: "{{ root_url_split.scheme }}"
    root_url_host: "{{ root_url_split.hostname }}"
    root_url_port: "{{ root_url_split.port | default(443 if root_url_split.scheme == 'https' else 80, true) }}"
    root_url_path: "{{ root_url_split.path | regex_replace('\\/$', '') }}/"

- name: validate root_url
  ansible.builtin.assert:
    that:
      - root_url_scheme in ('http', 'https')
      - root_url_host | length > 0
      - root_url_port | length > 0
      - root_url_path | length > 0
    fail_msg: libretime_public_url '{{ libretime_public_url }}' is invalid!

- name: install dependencies
  ansible.builtin.apt:
    state: present
    name: [git, make]
    update_cache: true

- name: checkout repository
  ansible.builtin.git:
    repo: "{{ libretime_checkout_url }}"
    dest: "{{ libretime_checkout_dest }}"
    version: "{{ libretime_checkout_version }}"
  register: libretime_checkout

- name: clean checkout # noqa no-handler command-instead-of-module
  ansible.builtin.command: git clean -xdf
  args:
    chdir: "{{ libretime_checkout_dest }}"
  when: libretime_checkout is changed

- name: build VERSION file
  ansible.builtin.command: make -C {{ libretime_checkout_dest }} VERSION
  args:
    creates: "{{ libretime_checkout_dest }}/VERSION"

- ansible.builtin.import_tasks: postgresql.yml
  when: libretime_postgresql_install

- ansible.builtin.import_tasks: rabbitmq.yml
  when: libretime_rabbitmq_install

- ansible.builtin.import_tasks: icecast.yml
  when: libretime_icecast_install

- ansible.builtin.import_tasks: liquidsoap.yml
  when: libretime_liquidsoap_install

- ansible.builtin.import_tasks: nginx.yml

- name: create {{ libretime_user }} user
  ansible.builtin.user:
    name: "{{ libretime_user }}"
    system: true
    createhome: false
    home: "{{ libretime_home }}"
  when: libretime_user != __default_web_user

- name: create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: directory
    recurse: true
  with_items:
    - path: "{{ libretime_home }}"
      owner: "{{ libretime_user }}"
      group: "{{ libretime_user }}"
    - path: "{{ libretime_log_dir }}"
      owner: "{{ libretime_user }}"
      group: "{{ libretime_user }}"
    - path: "{{ libretime_config_dir }}"
      # TODO: Config dir should not be writable, but liquidsoap writes to this dir.
      owner: "{{ libretime_user }}"
      group: "{{ libretime_user }}"

- name: deploy configuration file
  ansible.builtin.template:
    src: libretime/config.yml.j2
    dest: "{{ libretime_config_filepath }}"
    owner: "{{ libretime_user }}"
    group: "{{ libretime_user }}"
    mode: 0640
    backup: true
  notify:
    - restart libretime-analyzer
    - restart libretime-api
    - restart libretime-playout
    - restart libretime-liquidsoap
    - restart libretime-worker

- name: install python3
  ansible.builtin.apt:
    state: present
    name: [python3, python3-pip]

- ansible.builtin.import_tasks: shared.yml
  when: >
    libretime_api_install or
    libretime_worker_install or
    libretime_analyzer_install or
    libretime_playout_install

- ansible.builtin.import_tasks: api_client.yml
  when: >
    libretime_api_install or
    libretime_worker_install or
    libretime_analyzer_install or
    libretime_playout_install

- ansible.builtin.import_tasks: api.yml
  when: libretime_api_install

- ansible.builtin.import_tasks: worker.yml
  when: libretime_worker_install

- ansible.builtin.import_tasks: analyzer.yml
  when: libretime_analyzer_install

- ansible.builtin.import_tasks: playout.yml
  when: libretime_playout_install

- ansible.builtin.import_tasks: legacy.yml
  when: libretime_legacy_install

- ansible.builtin.import_tasks: _systemd.yml
  vars:
    service_name: libretime.target

- ansible.builtin.import_tasks: setup.yml
  when: libretime_setup
