---
- name: Install nginx
  ansible.builtin.apt:
    state: present
    name: [nginx]

- name: Disable default vhost
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Deploy nginx conf
  ansible.builtin.template:
    src: nginx/libretime.conf.j2
    dest: /etc/nginx/sites-available/libretime.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: Restart nginx

- name: Enable nginx conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/libretime.conf
    dest: /etc/nginx/sites-enabled/libretime.conf
    state: link
  notify: Restart nginx

- name: Check nginx config
  ansible.builtin.shell: /usr/sbin/nginx -t > /dev/null
  changed_when: false
