---
- ansible.builtin.import_tasks: _dependencies.yml
  vars:
    packages_path: "{{ libretime_checkout_dest }}/playout"

- name: install playout python package # noqa no-handler
  ansible.builtin.pip:
    name: "file://{{ libretime_checkout_dest }}/playout"
    state: latest # noqa package-latest
  notify: restart libretime
  when: libretime_checkout is changed

- name: create playout home directory
  ansible.builtin.file:
    path: "{{ libretime_home }}/playout"
    owner: "{{ libretime_user }}"
    group: "{{ libretime_user }}"
    state: directory
    recurse: true

- name: deploy liquidsoap logrotate config
  ansible.builtin.template:
    src: logrotate/libretime-liquidsoap.conf.j2
    dest: /etc/logrotate.d/libretime-liquidsoap
    owner: root
    group: root
    mode: 0644

- ansible.builtin.import_tasks: _systemd.yml
  vars:
    service_name: libretime-playout.service
  notify: restart libretime

- ansible.builtin.import_tasks: _systemd.yml
  vars:
    service_name: libretime-liquidsoap.service
  notify: restart libretime
