---
- name: Install postgresql
  ansible.builtin.apt:
    state: present
    name: [postgresql, postgresql-client, python3-psycopg2]

- name: Setup database
  become: true
  become_user: postgres
  block:
    - name: Create postgresql database user
      community.postgresql.postgresql_user:
        name: "{{ libretime_postgresql_user }}"
        password: "{{ libretime_postgresql_password }}"

    - name: Create postgresql database
      community.postgresql.postgresql_db:
        name: "{{ libretime_postgresql_name }}"
        encoding: UTF-8
        template: template0
        owner: "{{ libretime_postgresql_user }}"
