---
- name: Install rabbitmq
  ansible.builtin.apt:
    state: present
    name: [rabbitmq-server]

- name: Setup rabbitmq
  block:
    - name: Create rabbitmq vhost
      community.rabbitmq.rabbitmq_vhost:
        name: "{{ libretime_rabbitmq_vhost }}"
        state: present

    - name: Create rabbitmq user
      community.rabbitmq.rabbitmq_user:
        user: "{{ libretime_rabbitmq_user }}"
        password: "{{ libretime_rabbitmq_password }}"
        vhost: "{{ libretime_rabbitmq_vhost }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
