---
- name: Install shared python package # noqa no-handler
  ansible.builtin.pip:
    name: >
      libretime-shared
      @ file://{{ libretime_checkout_dest }}/shared
    state: latest # noqa package-latest
    virtualenv: "{{ libretime_venv_dir }}"
  notify: Restart libretime
  when: libretime_checkout is changed
