---
- name: install shared python package # noqa no-handler
  ansible.builtin.pip:
    name: "file://{{ libretime_checkout_dest }}/shared"
  notify:
    - restart libretime-analyzer
    - restart libretime-playout
    - restart libretime-liquidsoap
  when: libretime_checkout is changed
