---
collections:
  - name: containers.podman # https://github.com/containers/ansible-podman-collections
    version: 1.11.0
  - name: ansible.posix # https://github.com/ansible-collections/ansible.posix
    version: 1.5.2
