---
# The order of the handlers matters

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: restart php-fpm
  ansible.builtin.systemd:
    name: "php{{ __php_default_version }}-fpm"
    state: restarted

- name: restart icecast
  ansible.builtin.systemd:
    name: icecast2
    state: restarted

- name: restart libretime-api
  ansible.builtin.systemd:
    name: libretime-api
    state: restarted
  when: libretime_allow_restart

- name: restart libretime-playout
  ansible.builtin.systemd:
    name: libretime-playout
    state: restarted
  when: libretime_allow_restart

- name: restart libretime-liquidsoap
  ansible.builtin.systemd:
    name: libretime-liquidsoap
    state: restarted
  when: libretime_allow_restart

- name: restart libretime-worker
  ansible.builtin.systemd:
    name: libretime-worker
    state: restarted
  when: libretime_allow_restart

- name: restart libretime-analyzer
  ansible.builtin.systemd:
    name: libretime-analyzer
    state: restarted
  when: libretime_allow_restart
