---
# The order of the handlers matters

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: restart php-fpm
  ansible.builtin.systemd:
    name: "php{{ __php_default_version }}-fpm"
    state: restarted

- name: restart icecast
  ansible.builtin.systemd:
    name: icecast2
    state: restarted

- name: restart libretime
  ansible.builtin.systemd:
    name: libretime.target
    state: restarted
  when: libretime_allow_restart
