---
# The order of the handlers matters

- name: restart apache2
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: restart icecast
  ansible.builtin.systemd:
    name: icecast2
    state: restarted

- name: restart libretime-api
  ansible.builtin.systemd:
    name: libretime-api
    state: restarted
  when: libretime_allow_restart

- name: run libretime-api database migration
  become: true
  become_user: "{{ libretime_user }}"
  ansible.builtin.command: libretime-api migrate

- name: restart libretime-playout
  ansible.builtin.systemd:
    name: libretime-playout
    state: restarted
  when: libretime_allow_restart

- name: restart libretime-liquidsoap
  ansible.builtin.systemd:
    name: libretime-liquidsoap
    state: restarted
  when: libretime_allow_restart

- name: restart libretime-worker
  ansible.builtin.systemd:
    name: libretime-worker
    state: restarted
  when: libretime_allow_restart

- name: restart libretime-analyzer
  ansible.builtin.systemd:
    name: libretime-analyzer
    state: restarted
  when: libretime_allow_restart
