---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Bypass deb.debian.org repository
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: 'http:\/\/deb\.debian\.org'
        replace: "http://cdn-fastly.deb.debian.org"

    - name: Setup apt proxy
      ansible.builtin.apt:
        state: present
        name: auto-apt-proxy
        update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        state: present
        name: [git, make, acl] # Is acl only required while testing ?
        update_cache: true

    - name: Include libretime
      ansible.builtin.include_role:
        name: ansible-role-libretime
      vars:
        libretime_public_url: http://192.168.121.10:{{ libretime_listen_port }}/
        libretime_listen_port: 8888
