---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: bypass deb.debian.org repository
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: 'http:\/\/deb\.debian\.org'
        replace: "http://cdn-fastly.deb.debian.org"

    - name: install dependencies
      ansible.builtin.apt:
        state: present
        name:
          - git
          - make
          - auto-apt-proxy
          - acl # Is this only required while testing ?
        update_cache: true

    - name: include libretime
      ansible.builtin.include_role:
        name: ansible-role-libretime
      vars:
        libretime_public_url: http://{{ ansible_default_ipv4.address }}:{{ libretime_listen_port }}/
        libretime_listen_port: 8888
