---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  tasks:
    # - name: Setup apt proxy
    #   when: lookup("env", "CI") != "true"
    #   block:
    #     - name: Bypass deb.debian.org repository
    #       ansible.builtin.replace:
    #         path: /etc/apt/sources.list
    #         regexp: 'http:\/\/deb\.debian\.org'
    #         replace: "http://cdn-fastly.deb.debian.org"

    #     - name: Install auto-apt-proxy
    #       ansible.builtin.apt:
    #         state: present
    #         name: auto-apt-proxy
    #         update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        state: present
        name: [git, make, acl] # Is acl only required while testing ?
        update_cache: true

    - name: Link /usr/bin/sh to /bin/bash
      ansible.builtin.file:
        src: /bin/bash
        dest: /usr/bin/sh
        state: link

    - name: Include libretime
      ansible.builtin.include_role:
        name: ansible-role-libretime
