---
driver:
  name: podman

platforms:
  - &instance
    name: instance1
    image: ${MOLECULE_IMAGE:-debian:bullseye}
    dockerfile: Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    override_command: false
    systemd: always

  - <<: *instance
    name: instance2

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_PIPELINING: true
    # ANSIBLE_VERBOSITY: 1
    # ANSIBLE_STDOUT_CALLBACK: community.general.yaml
  inventory:
    host_vars:
      instance1:
        libretime_public_url: http://localhost:{{ libretime_listen_port }}/
        libretime_listen_port: 9001
        libretime_api_key: hackme
        libretime_secret_key: hackme
        libretime_playout_pip_extras: [sentry]
        libretime_playout_systemd_override: |
          [Service]
          Environment=LIBRETIME_LOG_LEVEL=debug
        libretime_systemd_hardening: false
      instance2:
        libretime_public_url: http://localhost:{{ libretime_listen_port }}/
        libretime_listen_port: 9002
        libretime_api_key: hackme
        libretime_secret_key: hackme
        libretime_systemd_hardening: false

verifier:
  name: testinfra
