---
driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: instance
    box: debian/bullseye64
    memory: 1024
    cpus: 2
    interfaces:
      - network_name: private_network
        ip: 192.168.121.10

provisioner:
  name: ansible

verifier:
  name: testinfra
