---
driver:
  name: podman

platforms:
  - &instance
    name: instance1
    image: ${MOLECULE_IMAGE:-debian:bullseye}
    dockerfile: Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    override_command: false
    systemd: always

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_PIPELINING: true
  inventory:
    host_vars:
      instance1:
        libretime_public_url: http://localhost:{{ libretime_listen_port }}/
        libretime_listen_port: 9001

verifier:
  name: testinfra
