name: CI

on:
  push:
    tags: ["v*.*.*"]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: make install
      - run: make lint

  test:
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          # TODO: re-enable once ansible-core 2.19 has been released
          # https://github.com/ansible/ansible/issues/84954
          # - ubuntu:focal
          - debian:bullseye

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.image }}
      cancel-in-progress: true

    steps:
      - run: podman info

      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/cache@v4
        with:
          path: |
            ~/.ansible/collections
            ~/.ansible/roles
          key: ${{ runner.os }}-ansible-${{ hashFiles('**/requirements.yml') }}

      - run: make install
      - run: make test
        env:
          PY_COLORS: true
          ANSIBLE_FORCE_COLOR: true
          MOLECULE_IMAGE: ${{ matrix.image }}
